# (1)
# application.yml 和 application.properties 的区别
# 1. 程序会先读取 .yml 再读取 .properties
# 2. 配置相同：.properties 会覆盖 .yml 的配置
# 3. 配置不同：两个都会生效
# 4. 结论：从优先级来说 application.properties > application.yml
# 问题：这里 port=7776，在 application.properties 中设置的 port=7777 到底谁会生效呢？
# 答案：7777生效

server:
  port: 7776

spring:
  datasource:
    # 1. 只要装了 ( mysql驱动 ) 和 ( jdbc数据库连接池 )，并且在这里配置好 ( 数据库连接池相关的配置项 ) 就能连接数据库
    # 2. mysql驱动 => mysql-connector-java
    # 3. jdbc连接池 => spring-boot-starter-jdbc
    # 4. 更进一步：还可以使用 ( Druid数据源 + MyBatis )
    url: jdbc:mysql://localhost:3306/7-react-admin-java?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    dirver-class-name: com.mysql.cj.jdbc.Driver
  jdbc:
    template:
      query-timeout: 10 # 10s没查出来就超时
  # redis:
    # remote
    # 可以通过 (external libraries)/spring-boot-autoconfigure:2.4.2/data/redis/RedisAutoConfiguration/RedisProperties/url 来查看
    # url = redis://user:password@example.com:6379
    # host: r-bp1z4zrytbuyv7mkuzpd.redis.rds.aliyuncs.com
    # port: 6379
    # password: woow_wu7:ALy123456789
    # client-type: Lettuce # 两种 ( Lettuce ) ( Jedis ) ，默认是 Lettuce
    # lettuce:
      # pool:
        # max-active: 10 # 连接池的最大连接书
        # min-idle: 5 # 最小空闲
  redis:
   # localhost
   host: localhost
   port: 6379
   password: root
   client-type: Lettuce # 两种redis连接工厂 ( Lettuce ) ( Jedis ) ，默认是 Lettuce
   lettuce:
    pool:
      max-active: 10 # 连接池的最大连接书
      min-idle: 5 # 最小空闲
  mvc:
    # 静态资源前缀
    # 值得注意的是前缀会导致 welcome静态文件夹的index.html失效
    # static-path-pattern: "/resources/**" # 增加静态资源前缀 resources
    static-path-pattern: "/**"
  # resources:
    # 指定子自定义的静态资源文件夹 ( 默认的静态资源文件夹路径 )
    # 1.
    # 当指定了 ( 前缀resources )，同时又指定了 ( 静态资源自定义的目录7resources )
    # 访问：http://localhost:7777/resources/7.jpg 就可以访问到静态资源
    # static-locations: [classpath:/7resources/]
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jackson:
    date-format: YYYY-MM-DD HH=mm=ss # 全局时间格式化
    time-zone: GMT+8 # 时区

mybatis:
  # 配置 mybatis 规则
  # 默认的前置路径就是 resources 文件夹中
  # 一个单词
  #   camel 是骆驼的意思
  #   external 是外部的意思 // external libraries外部仓库
  #   assistant 助理 // spring assistant spring助理
  #   framework 框架 // springframework 框架
  # config-location: classpath:mybatis/mybatis-config.xml # mybatis全局配置文件 ( 注意：如果有下面的 configuration 就要注释掉 config-location )
  mapper-locations: classpath:mybatis/mapper/*.xml # mybatis的sql映射文件，注意是 mapper-locations，有s
  configuration: # 配置规则，和 mybatis-config.xml 文件中配置是一样的效果，使用一种即可，即 ( configuration ) 或者 ( config-location ) 二选一
    map-underscore-to-camel-case: true


thymeleaf:
  # 配置 src/main/resources/templates/xxx.html 中的 html文件
  cache: false
  mode: LEGACYHTML5
  prefix: classpath:/templates/
  suffix: .html

myapp:
  # 自定义的配置参数，这里主要用来验证 @ConfigurationProperties 注解的使用
  author: woow_wu7
  name: react-admin-java
  email: woow.wu7@gmail.com
